env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    import/extensions: ['error', 'never', { 'tsx': 'never', 'ts': 'never', 'js': 'never', 'jsx': 'never' }],
    react/jsx-filename-extension: [1, { 'extensions': ['.tsx', '.ts', '.jsx'] }],
    react/destructuring-assignment: [0],
    no-unused-vars: 0,
    no-unused-expressions: 0,
    react/prop-types: [0],
    no-use-before-define: [0],
    no-plusplus: 0,
    react/jsx-props-no-spreading: [1],
    jsx-a11y/label-has-associated-control: off,
    jsx-a11y/click-events-have-key-events: off,
    jsx-a11y/no-static-element-interactions: off,
    jsx-a11y/anchor-is-valid: off,
  }
